### ISSUE TITLE
Network File outputs invalid Table

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3-network#160]
When dragging Network Explorer from Network File it works. When dragging other widgets (e.g. table) it crashes. This happens only on some computers with some network files.

```
-------------------------- AttributeError Exception ---------------------------
Traceback (most recent call last):
  File "/home/orange/.conda/envs/orange4/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 718, in __process_next
    self.process_queued()
  File "/home/orange/.conda/envs/orange4/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 476, in process_queued
    self.process_node(node_update_front[0])
  File "/home/orange/.conda/envs/orange4/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 523, in process_node
    self.send_to_node(node, signals_in)
  File "/home/orange/.conda/envs/orange4/lib/python3.6/site-packages/orangewidget/workflow/widgetsscheme.py", line 775, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/home/orange/.conda/envs/orange4/lib/python3.6/site-packages/orangewidget/workflow/widgetsscheme.py", line 809, in process_signals_for_widget
    handler(*args)
  File "/home/orange/git/orange3/Orange/widgets/data/owtable.py", line 491, in set_dataset
    self._setup_table_view(view, data)
  File "/home/orange/git/orange3/Orange/widgets/data/owtable.py", line 547, in _setup_table_view
    datamodel = RichTableModel(data)
  File "/home/orange/git/orange3/Orange/widgets/data/owtable.py", line 54, in __init__
    super().__init__(sourcedata, parent)
  File "/home/orange/git/orange3/Orange/widgets/utils/itemmodels.py", line 696, in __init__
    self.domain = domain = sourcedata.domain
AttributeError: 'numpy.ndarray' object has no attribute 'domain'
-------------------------------------------------------------------------------
```

Network version: 1.4.2<1.5.0. Using version with last commit from 18th September: "Pajek reader ...".

**Comment by ajdapretnar** [comment]
This seems more like a Data Table issue rather than Network.

**Comment by janezd** [comment]
I believe it's Network file's issue: I suspect (without looking at the code yet) that it stores labels as numpy.array instead of Table.

**Comment by janezd** [comment]
We miss you, @Hrovatin! :)

**Comment by Hrovatin** [comment]
Same, biolab was great. :D
