### ISSUE TITLE
Browse documentation networks ...

### ISSUE THREAD

**Issue by thocevar** [biolab/orange3-network#187]
doesn't work in Network File. I get the following version conflict error. You have to know the location and browse to that folder manually.

```
orange3-network\orangecontrib\network\widgets\OWNxFile.py", line 98, in browse_net_file
    startfile = next(load_entry_point(
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2460, in load
    self.require(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2483, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Cython 0.29.21 (c:\python\python38\lib\site-packages), Requirement.parse('Cython==0.29.14'), {'gensim'})
```

**Comment by ajdapretnar** [comment]
It works for me and I have just re-installed the entire add-on. 🤔 I have a different issue. Once I load the data set, the file selection window stays open and greyed out. I have to force-quit it to get it to close. Related?

**Comment by thocevar** [comment]
No, that's a separate issue. In my case file browser doesn't even open because of the failed version conflict.

**Comment by janezd** [comment]
I get a similar error as @thocevar, except that for me it's pyqtgraph:

```
Original exception was:
Traceback (most recent call last):
  File "/Users/janez/addons/orange-widget-base/orangewidget/gui.py", line 1925, in __call__
    self.func(**kwds)
  File "/Users/janez/addons/orange3-network/orangecontrib/network/widgets/OWNxFile.py", line 126, in select_net_file
    self.browse_net_file(True)
  File "/Users/janez/addons/orange3-network/orangecontrib/network/widgets/OWNxFile.py", line 101, in browse_net_file
    "network")())[1]
  File "/Users/janez/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/janez/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/janez/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/Users/janez/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/janez/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyqtgraph 0.10.0 (/Users/janez/miniconda3/envs/o3/lib/python3.7/site-packages), Requirement.parse('pyqtgraph==0.11.0'), {'Orange3'})
```

As for the problem reported by @ajdapretnar, I get this occasionally, too. If I cancel the dialog, close Orange and reopen, it works. I believe I've seen this elsewhere, too, so it might be Qt or even macOS issue. This is a native macOS dialog.

**Comment by ajdapretnar** [comment]
For me, restarting doesn't work. And I've only seen it in Network File. It's like something forgets to close the windows. The file is loaded normally.

**Comment by janezd** [comment]
@thocevar, this is probably due to broken installation. I upgraded my pyqtgraph to 0.11, as required by Orange, and now *Browse documentation* works.

In your case, you have a new version of Cython, while gensim kindly does this

```python
# We pin the Cython version for reproducibility.  We expect our extensions
# to build with any sane version of Cython, so we should update this pin
# periodically.
#
CYTHON_STR = 'Cython==0.29.21'
```

**Comment by thocevar** [comment]
True. But how can a problem like that pop-up in this case? What does "browsing documentation networks" have to do with dependencies (while the rest of Orange doesn't)?

**Comment by janezd** [comment]
Default directory is determined by

```python
            startfile = next(load_entry_point(
                "Orange3-Network",
                "orange.data.io.search_paths",
                "network")())[1]
```

This is nice, but the problem is that it checks requirements and finds the inconsistency.
