### ISSUE TITLE
Cannot Install Orange3-Network on Windows

### ISSUE THREAD

**Issue by iagovar** [biolab/orange3-network#36]
Hi, here's the error I get:

```
Collecting Orange3-Network
  Using cached Orange3-Network-1.2.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): networkx>=1.10 in c:\python34\lib\site-packages (from Orange3-Network)
Requirement already satisfied (use --upgrade to upgrade): pyqtgraph>=0.9.10 in c:\python34\lib\site-packages (from Orange3-Network)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in c:\python34\lib\site-packages (from networkx>=1.10->Orange3-Network)
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\python34\lib\site-packages (from pyqtgraph>=0.9.10->Orange3-Network)
Installing collected packages: Orange3-Network
  Running setup.py install for Orange3-Network: started
    Running setup.py install for Orange3-Network: finished with status 'error'
    Complete output from command C:\Python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\iagovar\\AppData\\Local\\Temp\\pip-build-btitb11u\\Orange3-Network\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\iagovar\AppData\Local\Temp\pip-19lq6ns1-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "orangecontrib.network._fr_layout" sources
    build_src: building npy-pkg config files
    running build_py
    creating build
    creating build\lib.win32-3.4
    creating build\lib.win32-3.4\orangecontrib
    copying orangecontrib\__init__.py -> build\lib.win32-3.4\orangecontrib
    creating build\lib.win32-3.4\orangecontrib\network
    copying orangecontrib\network\community.py -> build\lib.win32-3.4\orangecontrib\network
    copying orangecontrib\network\network.py -> build\lib.win32-3.4\orangecontrib\network
    copying orangecontrib\network\readwrite.py -> build\lib.win32-3.4\orangecontrib\network
    copying orangecontrib\network\setup.py -> build\lib.win32-3.4\orangecontrib\network
    copying orangecontrib\network\__init__.py -> build\lib.win32-3.4\orangecontrib\network
    creating build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\graphview.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxAnalysis.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxClustering.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxExplorer.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxFile.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxFromDistances.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxGenerator.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\__init__.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    creating build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\airtraffic.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\airtraffic_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\dicty_publication.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\dicty_publication_edges.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\dicty_publication_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\lastfm.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\lastfm.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\lastfm_all.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\lastfm_tags.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_by_genesets.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_by_genesets_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_by_pmid.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_by_pmid_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_huttenhower_a.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_huttenhower_a_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\makeNetworkList.py -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\mips_c2_cp_leu.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\mips_c2_cp_leu_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\network_info.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    creating build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\button_autoscale.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\button_rect.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Category-Network.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_clear.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_HideSelection.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_Mark2Sel.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_Sel2Mark.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_SelisMark.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_UnselectedNodes.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkAnalysis.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkClustering.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkExplorer.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkFile.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkFromDistances.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkGenerator.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    running build_ext
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    customize MSVCCompiler
    Missing compiler_cxx fix for MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'orangecontrib.network._fr_layout' extension
    compiling C sources
    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).
    
    ----------------------------------------
Command "C:\Python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\iagovar\\AppData\\Local\\Temp\\pip-build-btitb11u\\Orange3-Network\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\iagovar\AppData\Local\Temp\pip-19lq6ns1-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\iagovar\AppData\Local\Temp\pip-build-btitb11u\Orange3-Network\
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

I tried with pip in the command line for python3, but I'm not a programmer and did achieve nothing :(

**Comment by ajdapretnar** [comment]
Strangely, this used to work out of the box with Anaconda. Now you just need to install [Visual Studio compiler](http://landinghub.visualstudio.com/visual-cpp-build-tools) as well and run the same pip install command again. It should work without problems.

I'm keeping this issue open since we should investigate why Anaconda is suddenly misbehaving.

**Comment by iagovar** [comment]
I have Visual Studio Community 2015, still the same error :/

**Comment by ajdapretnar** [comment]
I don't know, perhaps you are missing it in the PATH variable? Could you check your environment variables and specify what you see in VS140COMNTOOLS (or sth similar)?

**Comment by ajdapretnar** [comment]
Also, try using [Anaconda](https://www.continuum.io/downloads), since it might link the dependencies better.

**Comment by iagovar** [comment]
Mmm, I'm looking in the PATH Variable and I don't see that entry. I downloaded Rapid enviroment Editor just for convenience, and It still nothing. I see the Path for Python34 but nothing about VS140COMNTOOLS  or similar.

**Comment by astaric** [comment]
You could try installing the pre-built package from https://anaconda.org/ales-erjavec/Orange3-Network

```
pip install -i https://pypi.anaconda.org/ales-erjavec/simple orange3-network
```

**Comment by astaric** [comment]
PS.: native conda packages are coming in a day or two: https://github.com/conda-forge/orange3-network-feedstock

**Comment by iagovar** [comment]
Hi all, I finally managed to install it via Conda, but it doesn't appear inside Orange :/

**Comment by ajdapretnar** [comment]
@iagovar Is this still an issue?

@astaric I do have people reporting installation via conda passes, but add-ons don't appear in the pane. Could it be the issue of conflicting paths on Windows or what? 😕

**Comment by processo** [comment]
I've been having the same issue with Network and Timeseries. @astaric's solution worked for Network. Didn't need Visual C++ 10.0 and it showed up after restart. Thanks.

In the Add-ons list first Orange said it was an outdated one (1.1.2 < 1.2.0), now they are separate add-ons.

**Comment by sh9g14** [comment]
I solved this by using:
conda install orange3-network

Nothing else worked!

**Comment by processo** [comment]
@sh9g14 https://github.com/biolab/orange3-network/issues/36#issuecomment-281068938 doesn't work to me either anymore. Install fails with:
```error: Microsoft Visual C++ 10.0 is required. Get it with "Microsoft Windows SDK 7.1": www.microsoft.com/download/details.aspx?id=8279```

Having Windows SDK 7.1 still gives an error:
```
Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Program Files\Orange\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Program Files\Orange\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Program Files\Orange\lib\site-packages\pip\req\req_install.py", line 922, in install
    with open(inst_files_path, 'w') as f:
OSError: [Errno 22] Invalid argument: '"C:\\Program Files\\Orange\\Lib\\site-packages\\Orange3_Network-1.3.2-py3.4.egg-info\\installed-files.txt'
```
but _Network_ shows up and **workes perfectly after restart**.

**Comment by muba1** [comment]
had the same problem but this one works for me.
