### ISSUE TITLE
Error when trying to open Vertices data file

### ISSUE THREAD

**Issue by vodopma** [biolab/orange3-network#48]
If I open the system dialog for loading a Vertices data file (...) in **Network File** and then close it without choosing a file  (..I do this for example if I want to check what data formats are supported), I get an error and Networks stops functioning. 

_workaround:_ reset widget settings and restart Orange

----------------------------------------
```
Exception:
TypeError: expected str, bytes or os.PathLike object, not tuple
Module:
ntpath:204
Widget Name:
Network File
Widget Module:
orangecontrib.network.widgets.OWNxFile:267
Widget Scheme:
C:\Users\vodopma2\AppData\Local\Temp\ows-x6bs9p57.ows.xml
Version:
3.8.0
Environment:
Python 3.6.3 on Windows 7 6.1.7601 x86
Installed Packages:
AnyQt==0.0.8, Bottleneck==1.2.1, CommonMark==0.7.4, Orange3-Network==1.3.0, Orange3==3.8.0, PySocks==1.6.7, asn1crypto==0.23.0, certifi==2017.11.5, cffi==1.11.2, chardet==3.0.4, cryptography==2.1.4, decorator==4.1.2, dill==0.2.7.1, docutils==0.14, future==0.16.0, idna==2.6, joblib==0.11, keyring==9.0, keyrings.alt==2.3, networkx==2.0, numpy==1.13.3, pip==9.0.1, pyOpenSSL==17.5.0, pycparser==2.18, pyqtgraph==0.10.0, pyreadline==2.1, pywin32==221, requests==2.18.4, scikit-learn==0.19.1, scipy==0.19.1, serverfiles==0.2.1, setuptools==36.5.0.post20170922, six==1.11.0, urllib3==1.22, wheel==0.30.0, win-inet-pton==1.0.1, wincertstore==0.2, xlrd==1.1.0
Machine ID:
118796715501792
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\site-packages\orangecontrib\network\widgets\OWNxFile.py", line 267, in browseDataFile
    self.populate_comboboxes()
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\site-packages\orangecontrib\network\widgets\OWNxFile.py", line 102, in populate_comboboxes
    self.datacombo.addItem(path.basename(file))
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\ntpath.py", line 235, in basename
    return split(p)[1]
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\ntpath.py", line 204, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not tuple

Local Variables:
OrderedDict([('p', ('', ''))])
```

**Comment by jerneju** [comment]
Fixed in #50 .
