### ISSUE TITLE
Error when connecting Network File to Explorer

### ISSUE THREAD

**Issue by vodopma** [biolab/orange3-network#49]
Data is successfully loaded, but an error appears when trying to connect it to the **Network Explorer** widget. Error can be ignored, and the graph is plotted, but is very persistent even after.

![image](https://user-images.githubusercontent.com/34769451/34296895-34cee3ce-e715-11e7-9e6c-9074d1c1fc37.png)

--------------------------
```
Exception:
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
Module:
Orange.data.table:452
Widget Name:
Network Explorer
Widget Module:
orangecontrib.network.widgets.OWNxExplorer:237
Widget Scheme:
C:\Users\vodopma2\AppData\Local\Temp\ows-kwpl4ho6.ows.xml
Version:
3.8.0
Environment:
Python 3.6.3 on Windows 7 6.1.7601 x86
Installed Packages:
AnyQt==0.0.8, Bottleneck==1.2.1, CommonMark==0.7.4, Orange3-Network==1.3.0, Orange3==3.8.0, PySocks==1.6.7, asn1crypto==0.23.0, certifi==2017.11.5, cffi==1.11.2, chardet==3.0.4, cryptography==2.1.4, decorator==4.1.2, dill==0.2.7.1, docutils==0.14, future==0.16.0, idna==2.6, joblib==0.11, keyring==9.0, keyrings.alt==2.3, networkx==2.0, numpy==1.13.3, pip==9.0.1, pyOpenSSL==17.5.0, pycparser==2.18, pyqtgraph==0.10.0, pyreadline==2.1, pywin32==221, requests==2.18.4, scikit-learn==0.19.1, scipy==0.19.1, serverfiles==0.2.1, setuptools==36.5.0.post20170922, six==1.11.0, urllib3==1.22, wheel==0.30.0, win-inet-pton==1.0.1, wincertstore==0.2, xlrd==1.1.0
Machine ID:
118796715501792
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\site-packages\orangecontrib\network\widgets\OWNxExplorer.py", line 237, in on_selection_change
    self.commit()
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\site-packages\Orange\widgets\gui.py", line 2001, in unconditional_commit
    do_commit()
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\site-packages\Orange\widgets\gui.py", line 2009, in do_commit
    commit()
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\site-packages\orangecontrib\network\widgets\OWNxExplorer.py", line 276, in commit
    self.send_data()
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\site-packages\orangecontrib\network\widgets\OWNxExplorer.py", line 412, in send_data
    self.send(Output.REMAINING, items[remaining, :] if remaining else None)
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\site-packages\Orange\data\table.py", line 743, in __getitem__
    return self.from_table(domain, self, row_idx)
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\site-packages\Orange\data\table.py", line 361, in from_table
    table = cls.from_table_rows(source, row_indices)
  File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\site-packages\Orange\data\table.py", line 452, in from_table_rows
    self.X = source.X[row_indices]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by thocevar** [comment]
The relevant input files: [A.zip](https://github.com/biolab/orange3-network/files/1582488/A.zip)

**Comment by kernc** [comment]
I assume the issue is:
```
File "C:\Users\vodopma2\AppData\Local\Orange_3-8\lib\site-packages\orangecontrib\network\widgets\OWNxExplorer.py", line 412, in send_data
    self.send(Output.REMAINING, items[remaining, :] if remaining else None)
```
`remaining` being a list of floats.

**Comment by kernc** [comment]
Could you check if you edit the line to:
```py
self.send(Output.REMAINING, items[np.array(remaining, dtype=int), :] if remaining else None)
```

**Comment by janezd** [comment]
Widget has been reimplemented from scratch.
